name: localization
description: Dart package which manages localization of the app
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/translations/